### ISSUE TITLE
Can there be only one Sphinx .. _index: directive on a deconst local build?

### ISSUE THREAD

**Issue by annegentle** [deconst/client#44]
I've seen this every time I've tried to build a local copy of a 2nd user guide, in this case from https://github.com/rackerlabs/rs-heat-docs/pull/23 and the master branch of https://github.com/rackerlabs/docs-core-infra-user-guide. I don't get a sidebar TOC for the 2nd user guide built.
I'm using this as my nexus-control: https://github.com/annegentle/nexus-control/tree/add-heat

How to reproduce:
Version 4 of deconst client
nexus-control: https://github.com/annegentle/nexus-control/tree/add-heat
1st user guide: https://github.com/rackerlabs/rs-heat-docs/pull/23
2nd user guide: https://github.com/rackerlabs/docs-core-infra-user-guide
Build with the deconst client.
Open each built user guide in a browser.
Seems like only the 1st guide has a properly requested toc that then appears in the local rendering of the content.

Use docker log <id> to see that the 1st user guide has:
2015-10-17T03:32:19.847Z - debug: Content service request: [http://content:8080/content/https%3A%2F%2Fgithub.com%2Frackerlabs%2Frs-heat-docs%2F_toc]
2nd user guide has:
2015-10-17T03:31:54.792Z - debug: Content service request: [http://content:8080/content/local-content%2F_toc]

**Comment by smashwilson** [comment]
Er, I'm seeing TOCs for both guides. I'm building from the forks and branches that you name:

_nexus-control @ annegentle/add-heat, 07c4e1d_
_rs-heat-docs @ annegentle/build-files, 2525691_
_docs-core-infra-guide @ master, 768d241_

![screen shot 2015-10-19 at 8 39 00 am](https://cloud.githubusercontent.com/assets/17565/10578004/5899a438-763d-11e5-9626-e5e893a62fcf.jpeg)

![screen shot 2015-10-19 at 8 39 07 am](https://cloud.githubusercontent.com/assets/17565/10578005/5b602dcc-763d-11e5-9938-51ba23aec74a.jpeg)

> [..] I don't get a sidebar TOC [..]

Usually this means that there's a mismatch between the template chosen and the builder used in `conf.py`.

Were you messing around with the control repository mappings while the client was still running? Due to some wonkiness in the presenter, changes to templates or any of the mappings only take effect when the client is restarted.

**Comment by annegentle** [comment]
Thanks for testing. I always did Cmd+Q and/or `docker-machine <name> stop`, and the mappings are the first thing I did anyway.

What do you think is the cause of `Content service request: [http://content:8080/content/local-content%2F_toc]` happening? Doesn't seem like I need `_deconst.json` in the docs-core-infra-user-guide, since it's working on the site itself.

**Comment by smashwilson** [comment]
> Thanks for testing. I always did Cmd+Q and/or docker-machine <name> stop, and the mappings are the first thing I did anyway.

:+1: Just making sure. It's been the biggest source of confusion for me.

> What do you think is the cause of Content service request: [http://content:8080/content/local-content%2F_toc] happening?

That's our hack for supporting TOCs in non-single-page content repositories. It's expected and should be working as intended, assuming that the rest of that log doesn't show a 404 for the `_toc` document.

Essentially, when we build a multi-page content repository, we also submit a special TOC document at the "root" of the content ID space. Every time you view a page on deconst, the content service is queried for the content for your presented URL itself, _and_ for a `_toc` document at the root of its content ID (which is bad - it's otherwise a rule that **nothing** about the content ID structure is assumed). If a `_toc` document is found successfully, then that TOC is made available to the templates.

As deconst/deconst-docs#133 describes, I want to provide a mechanism to submit content in atomic batches, with metadata such as a TOC associated with the entire upload. The content service could then provide the TOC naturally with the rest of the metadata envelope it's constructing, and we'd save ourselves an extra request. We're not there yet, though.

> Doesn't seem like I need _deconst.json in the docs-core-infra-user-guide, since it's working on the site itself.

You don't have a `_deconst.json` file in docs-core-infra-user-guide? I do:

``` bash
$ ls ~/writing/docs-core-infra-user-guide/ | grep ^_
_build
_common
_deconst.json
_images
_toc.rst
$ cat ~/writing/docs-core-infra-user-guide/_deconst.json 
{
  "contentIDBase": "https://github.com/rackerlabs/docs-core-infra-user-guide/"
}
```

That might be the source of your problems; docs-core-infra-user-guide could be "half-mapped" for you somehow. It would also explain why you're seeing "local-content" as the content ID; that's the synthetic content ID base I use in the client when I don't have a real one to use.

What SHA is your docs-core-infra-user-guide repo on? The quickest way to find out is:

``` bash
cd ${WHATEVER}/docs-core-infra-user-guide
git rev-parse --short HEAD
```

Also, is the client prompting you to choose a template for docs-core-infra-user-guide? What template are you choosing?

**Comment by annegentle** [comment]
Ah, that was it, I updated my master branch and see `Updating 6b3821f..768d241` so for sure I'm in that half-mapped state. Thanks!

**Comment by annegentle** [comment]
Reopening because the TOC not showing up for the orchestration user guide happened again today and it's happening to @masthalter today also with the local client.

**Comment by smashwilson** [comment]
Okay, based on some digging in Slack, my current thought is that the `_toc` location code in the deconst presenter breaks for unmapped repositories, because the fake content ID it uses doesn't look like "real ones" (... and it shouldn't, because that helps us avoid collisions).

I'm hopeful that deconst/deconst-docs#133 will address this naturally, because I'm planning to include a less hacky way for a content repo's TOC to be submitted.

**Comment by smashwilson** [comment]
As a workaround until then, you should be able to map the repository and template in your control repository clone.

**Comment by annegentle** [comment]
I was able to get the sidebar toc once I had the routes in my local nexus-control.
